version: "3"

services:
  server:
    build: build/
    ports:
      - 5000:5000
#    depends_on:
#      - db
#  db:
#    image: store/oracle/database-enterprise:12.2.0.1
#    restart: always
#    ports:
#      - 5432:5432
#    volumes:
#      - db:/u01/app/oracle
#volumes:
#  db:
