name: form_app
description: A sample demonstrating different types of forms and best practices
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_map_location: ^0.7.0
  flutter_map: any
  flutter_map_marker_cluster: any
  google_maps_flutter: ^0.5.25+2
  location: ^3.0.1
  latlong: 0.6.1
  equatable: 0.1.1
  cupertino_icons: ^0.1.3
  intl: any
  http: ^0.12.0
  mockito: 4.1.1
  json_annotation: ^3.0.0
  english_words: ^3.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.0.0
  build_runner: ^1.10.0
flutter:
  uses-material-design: true
  assets:
    - images/background.png
    - images/logo.png
    - images/take_photo.png